---
version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./devdata/config:/config
      - ./devdata/cache:/cache
      - ./media:/media
    restart: 'unless-stopped'
    ports:
      - '8096:8096'
